[package]
name = "linearity"
description = "Library providing various operations commonly found in branchless programming"
license = "AGPL-3.0"
authors = ["advantageous-overtake"]
version = "1.0.0"
edition = "2021"

[dependencies]
paste = "1.0.15"

[dev-dependencies]
const-random = "0.1.18"
