name: build

on:
  push:
    branches:
      - edge
      - 'pr/**'
  repository_dispatch:
    types:
      - build

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build on ${{ matrix.os }} using rust ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
            - stable
            - beta
            - nightly
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
