name: test

on:
  push:
    branches:
      - edge
      - 'pr/**'
  repository_dispatch:
    types:
      - test

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test on ${{ matrix.os }} using rust ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --verbose  
